### ISSUE TITLE
How should arguments be handled (or not)?

### ISSUE THREAD

**Issue by kalley** [guymers/babel-plugin-flow-relay-query#12]
Given that any field can optionally take arguments in relay, is there a way to make this plugin able to consume that information? For example:

```graphql
fragment on Query {
  emailExists(email: $email)
}

fragment on Query {
  articles(author_id: $authorId) {
    name
  }
}
```

Where (in these examples) the values for those arguments is defined in `relay.variables`, but there might be reason to hardcode those specific to a component.

**Comment by guymers** [comment]
Probably the easiest solution would be to add some sort of `arguments` option to `FragmentOptions` that would work like the `directives` option.

**Comment by kalley** [comment]
Was looking at `relay`'s flowtype definitions and something [caught my eye](https://github.com/facebook/relay/blob/3cb82fecae6601b8a9ceed6c13e7c8254913ba35/scripts/babel-relay-plugin/src/__tests__/testschema.rfc.graphql#L72) that maybe we could use for some of this.

[Here's a small flowtype.org/try scenario that expands the AST for the following](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDCcAttgIYB2mYAvGAN6phi6nya64DOAFFAJYAnLugBcYCgFdiAI1yCAlOMYBIAcPQA5MsVziRg-hQDmAbiZgAvqktA)

```js
/* @flow */
type Company = {
  employees(first: number): {
	firstName: string;
  }
}
```

**Comment by kalley** [comment]
I'm wondering if it makes sense to export a type that can specify relay variables, similar to:

```js
/* @flow */
// this could be exported from this library and imported
type RelayVariable<V> = V

type Company = {
  employees(first: RelayVariable<'first'>): {
    edges: {
      node: {
        firstName: string;
        addresses(first: 2): {
          state: string;
        }
      }
    }
  }
}
```

which would build out to:

```graphql
fragment on Company {
  employees(first: $first) {
    edges {
      node {
        firstName
        addresses(first: 2) {
          state
        }
      }
    }
  }
}
```

**Comment by guymers** [comment]
That would be kind of cool, would it be a problem that Flow no thinks that your component is receiving a function in its props?

**Comment by kalley** [comment]
It looks like it would. I wonder if there's a way around that that I haven't yet thought of.

**Comment by kalley** [comment]
[Not entirely sure if this is much better, but I do like the contextualization of the arguments](
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBKuMAhpgGokBOAliQEYy4A85AfGALxjkY75FSmAApU4eKlgDqNdAAsAglQDmAVwC2uAHboAzswUAaMMI7dhqPnjABhOOuwktmLmADeqMGFwP4mXLi6AFyExGSi4riSmDLySmqaOvoeXl5QNFS66CGCZJS0DEzMAOTpmejFbJ5gAL7GKam4ACbKgSENqWBacE247dWdaRlZAHIkmiFZtFrKANwDgyRNTVSBum2hQhES0rKKKhraeswdg0PlIQBMC511N6mnZ1kk6H1gUzQz9141bADaAF17jUFjVAdVfqgQagAMZwLRZMBwhxOTAhOwo5yuBo+bB+ALBdwLZqtQl-R5dHpvCnnUbjN7FADSJBgTEwxUM3zASxWaw2fy5Xhpg2erxCxQAKgANYqC2pcgGcs4g25An5Q+5AA). This could lead into property level directives as well (or some combination thereof, which we have in our app).

It actually ends up looking pretty similar to how you define variables for an entire container in relay, so it might not be as bad as I think. I do however think it's better than my first alternate attempt, which looked like:

```js
type EmployeeConnection = {
  edges: {
    node: { 
      firstName: string;
    }
  }[]
}

type Company = {
  employees: EmployeeConnection | (first: 1) => EmployeeConnection
}
```

**Comment by guymers** [comment]
It looks intriguing, would it be annoying to have to go and change your types so they can parsed? Some people probably wouldn't mind, kind of like adding annotations for ORM/serialization. Personally I prefer having separation, but what I came up with doesn't overly excite me.

```
generateFragmentFromProps({
  arguments: {
    employees: {
      __args: { first: null },
      edges: {
        node: {
          address: {
            __args: { first: 2 }
          }
        }
      }
    }
  }
});
```

```
generateFragmentFromProps({
  arguments: [
    {
      employees: { first: null }
    },
    {
      employees: {
        edges: {
          node: {
            address: { first: 2 }
          }
        }
      }
    }
  ]
});
```

**Comment by kalley** [comment]
could you do something similar to `_.get`, where, instead of generating the shape for arguments, it looks more like (I guess it could go either way, with this just getting expanded to what's above):

```js
generateFragmentFromProps({
  arguments: [
    'employees': { first: null },
    'employees.edges.node.address': { first: 2 }
  ]
})
```

My only real issue is that there needs to be an indication of what variable maps. Since I could potentially have multiple `first`s that use different variables. I do agree that it is nice to have it closer to where you're actually defining variables. But I think there's an argument to be made that with flowtype you are already annotating, so why wouldn't you annotate everything at the same time. Even though this is like meta-annotating, which may just be overkill.

**Comment by guymers** [comment]
If you like the type encoding feel free to implement it as long as it's backwards compatible. Would you store the arguments as an additional field in `FlowObjectType`?
