### ISSUE TITLE
Issue with import and Webpack aliases

### ISSUE THREAD

**Issue by kalley** [guymers/babel-plugin-flow-relay-query#16]
When I import a file that has an aliased directory in webpack, the `utils/import` cannot resolve the paths. I made a change locally where I pass in a function to the plugin that helps the resolver, but it's a really naive implementation and I don't know this would just be handled by re-ordering plugins or something much easier.

Currently, my `.babelrc` looks like:

```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "Safari 8", "ChromeAndroid > 4"]
      },
      "loose": true,
      "modules": false,
      "useBuiltIns": true
    }],
    "react"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-proto-to-assign",
    "transform-undefined-to-void",
    "./relay-plugin"
  ]
}
```

**Comment by guymers** [comment]
I think the way you solved it is the only option given the aliases are contained within Webpack, Babel doesn't have any knowledge of them.
