### ISSUE TITLE
Do flowtypes work correctly when using this plugin?

### ISSUE THREAD

**Issue by brandonmp** [guymers/babel-plugin-flow-relay-query#3]
I've tried using `flow types` with `Relay`, but it seems that many `type errors` around props are consistently suppressed b/c of the HOC pattern the `Relay container` uses (specific to flow,[ see this SO question](http://stackoverflow.com/questions/39358847/how-to-type-an-exported-relaycontainer), and for flow and HOCs, see[ this repo issue](https://github.com/cssinjs/react-jss/issues/65) and [this repo issue](https://github.com/facebook/flow/issues/2521#issuecomment-270551040)

The problems are subtle because they're false positives (ie, missed errors), but they're pretty consistent. 

Does this plugin solve that? I poked around the `src` but couldn't conclude either way.

**Comment by guymers** [comment]
No this plugin won't help you with that problem. Its goal is to guarantee that the fragment matches the exact shape of your React components Prop type.

**Comment by brandonmp** [comment]
thanks @guymers.  it's a really good idea btw. coupled [with this extension,](https://github.com/brigand/babel-plugin-flow-react-proptypes) which turns `flowTypes` into `propTypes` at runtime, feels particularly efficient.
