### ISSUE TITLE
Use with an HoC

### ISSUE THREAD

**Issue by kalley** [guymers/babel-plugin-flow-relay-query#4]
So, we have a HoC around `Relay.createContainer` that allows us to subscribe to our Redux store for `setVariables`. This plugin appears to bypass that because it looking specifically for `Relay.createContainer` instead of the marker (which is what I was expecting).

Even if it was something similar to an alternative syntax where I pass the component along side the options, that would be a huge help:

```js
generateFragmentFromComponentProps(Component: React$Component, options?: FragmentOptions)
```

**Comment by guymers** [comment]
I've removed the explicit Relay.createContainer check and all the tests still pass. Would that work for your use case or does your HOC not follow the same parameters as Relay.createContainer?

**Comment by kalley** [comment]
Our HoC is written to be used like decorator, so it just takes the spec and then we call it with the component later. I can add an example if that would help.

**Comment by guymers** [comment]
An example would help, thanks.

**Comment by kalley** [comment]
So a common pattern we end up with is (fleshing out the example a bit so you see the why):

```
import _ from 'lodash
import { connect } from 'react-redux'
import createContainer, { Relay } from 'decorators/relay-container'

import type { RelayContainerSpec } from 'react-relay'

const SomeComponent = () => <div />

const relaySpec: RelayContainerSpec = {
  fragments: {
    thing: () => Relay.QL``,
  }
}

const compose = _.flow(
  connect(state => ({}), { someAction }),
  createContainer(relaySpec)
)

export default compose(SomeComponent)
```

Occasionally, we have Modal versions we also export that would share the same compose function and just pass all the props through to the original component.

If we need to inline the specs, that's okay. I was also going to take a stab at doing this (I forked the repo, just haven't had too much time as of yet to dig in).

**Comment by guymers** [comment]
With the removal of the explicit Relay.createContainer check in master could you just wrap compose into a function that takes a component and Relay options?

```js
const createRelayContainer = (component, relaySpec) => {
  const compose = _.flow(
    connect(state => ({}), { someAction }),
    createContainer(relaySpec)
  );
  return compose(component)
}

export default createRelayContainer(SomeComponent, {
  fragments: {
    thing: generateFragmentFromProps()
  }
})
```

**Comment by guymers** [comment]
I've added a new `generateFragmentFromPropsFor(component: ReactClass<*>, options?: FragmentOptions)` marker function like you suggested in order to get the plugin to work with Apollo. Let me know if it works for your use case, in theory you shouldn't have you change your codes formatting.

**Comment by kalley** [comment]
@guymers this works for me. Thanks!
